### ISSUE TITLE
Incorrect value at "isChrome", that is false during using chrome

### ISSUE THREAD

**Issue by jiwookseo** [ICJIA/vue-browser-detect-plugin#1]
```json
// $browserDetect
{ "isOpera": false, "isFirefox": false, "isSafari": false, "isIE": false, "isEdge": false, "isChrome": false, "isBlink": false, "meta": { "name": "Chrome", "version": "75", "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36" } }
```

**Comment by robhuska** [comment]
I have the same issue.

**Comment by cschweda** [comment]
Thanks. Should be fixed.

**Comment by robhuska** [comment]
hmmm... After updating to version 0.1.13I still get `false` when using `this.$browserDetect.isChrome`. I have been able to use a workaround with `this.$browserDetect.meta.name === 'Chrome'`.

**Comment by cschweda** [comment]
Thanks. Fixed. 

This is what I'm seeing with Chrome:

```
{ "isOpera": false, "isFirefox": false, "isSafari": false, "isIE": false, "isEdge": false, "isChrome": true, "isBlink": true, "meta": { "name": "Chrome", "version": "75", "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" } }
```

**Comment by robhuska** [comment]
Here is a screen shot from my console in Chrome.

![image](https://user-images.githubusercontent.com/2412155/61964099-2231ee00-af9b-11e9-8ad4-ccc78cf0714a.png)

**Comment by cschweda** [comment]
You bumped to version 0.1.4?

**Comment by robhuska** [comment]
no the latest I saw was 0.1.3. Let me check for another update.

**Comment by robhuska** [comment]
Ok that did it. This may be the wrong place to mention this, but what about mobile Chrome and Safari? iOS lists Chrome as Safari. Any plans for mobile browser support?

**Comment by cschweda** [comment]
Yes. I will add that shortly.

Thank you! :)
