### ISSUE TITLE
ie-Edge is not recognized.

### ISSUE THREAD

**Issue by hxgst2** [ICJIA/vue-browser-detect-plugin#43]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.64

string returns = chrome;v91

**Comment by cschweda** [comment]
Fixed.

**Comment by Nechitadi** [comment]
Are you sure @cschweda ? It recognizes that isEdge but the name in meta is 'Chrome'. I use  "vue-browser-detect-plugin": "^0.1.18"
![image](https://user-images.githubusercontent.com/27554509/145394929-db798768-fcea-41ad-8be8-0db05cf084a6.png)
